### ISSUE TITLE
Data relationship broken on Subsite admin

### ISSUE THREAD

**Issue by davejtoews** [WPP-Public/akqa-nz-silverstripe-menumanager#63]
Silverstripe: 5.2
Menumanager: 4.2.1

I am unable to click into an individual subsite from /admin/subsites. An "Internal Error" flag pops up. With error reporting on, the async call to the backend is returning:

`[Emergency] Uncaught Exception: No has_one found on class 'Heyday\MenuManager\MenuSet', the has_many relation from 'SilverStripe\Subsites\Model\Subsite' to 'Heyday\MenuManager\MenuSet' requires a has_one on 'Heyday\MenuManager\MenuSet'`

**Comment by wilr** [comment]
Thanks - see `MenuSubsiteExtension` which will add this.

**Comment by davejtoews** [comment]
🤦‍♂️Of course! Apologies for the noise. Upgraded from 3.x, things broke, and I should have dug in deeper before PRing.
