### ISSUE TITLE
Silverstripe 5 compatibility

### ISSUE THREAD

**Issue by mhenden** [WPP-Public/akqa-nz-silverstripe-menumanager#65]
I'm wanting to use this module with Silverstripe 5. Right now I've having compatibility problems (refuses to install). Any chance somebody can resolve this issue? Thanks.

>   Problem 1
    - heyday/silverstripe-menumanager[3.0.0-alpha, ..., 3.x-dev] require silverstripe/framework ~4.0 -> found silverstripe/framework[4.0.0-alpha1, ..., 4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires heyday/silverstripe-menumanager ^3.0 -> satisfiable by heyday/silverstripe-menumanager[3.0.0-alpha, ..., 3.x-dev].

**Comment by wilr** [comment]
You want to use `4.3` for Silverstripe 5. Based on that error it is trying to install 3.0 which only supports 4

**Comment by mhenden** [comment]
Thanks @wilr , that was the fix I needed!
